### ISSUE TITLE
[Feature Request] -e to disable htaccess

### ISSUE THREAD

**Issue by danmandle** [kfei/docktorrent#17]
It would be awesome to be able to pass in another environment variable to disable the htaccess and password. My docker instance is accessible only inside of my network and I'd rather not go in and manually disable it every time.

**Comment by kfei** [comment]
Thanks for the suggestion. Now you can turn off HTTP authentication on certain network by passing run time argument like `-e AUTH_OFF=192.168.1.0/24`.

Hava a nice day!
