### ISSUE TITLE
Docktorrent integration with upstart

### ISSUE THREAD

**Issue by kholisrag** [kfei/docktorrent#37]
hello, may I ask: what script that can use to docktorrent automatically start using upstart
this my script in /etc/init/docker-torrent.conf

description "Docker Container for ruTorrent RedCloud Server"
start on filesystem and started docker
stop on runlevel [!2345]
respawn
script
  exec docker run -it -p 8082:80 -p 45566:45566 -p 9527:9527/udp --dns 8.8.8.8 -v /home/gumelaragum/downloads:/rtorrent -e UPLOAD_RATE=1024 kfei/doc$
end script

but when I running with
start docker-torrent

and check with docker ps, it's not listed...

**Comment by Nightreaver** [comment]
Hey

you just use `docker run` to setup (a new) container with your config/prefrences - you should name it with --name

then you use `docker start [name]` to start an existing container

if you use `-it` you'll get a interactive shell and when you exit the shell, the container will also shut down (just my experience)
rather use `docker attach` alter

also check `-d` which is for daemonize/detachted, i think

list all your containers with `docker ps -a` (even not-running ones)

*correct me if I'm wrong
