### ISSUE TITLE
Automatic restarting of rTorrent not working 

### ISSUE THREAD

**Issue by jaysh** [kfei/docktorrent#7]
Hi,

Thanks for this useful project :)

I noticed one of the features listed is "rTorrent will automatically restarts on crash" - however it doesn't appear to be working for me. Occasionally, rTorrent will become entirely unresponsive and I have to `kill` it. But - it doesn't get restarted. Instead, the whole container shuts down.

Poking around, it seems like this is the intended behaviour: https://github.com/kfei/docktorrent/blob/e82e0ed48aa5579d718dda4c9cdadfcaaf1b77b1/rootfs/service/rtorrent/finish. Once `finish` gets called (i.e. if `rtorrent` exits), all the other services get killed. Is my interpretation correct?

If so, should it be fixed? The only way I worked around this to was to remove this line - and then remove the lock checking in `run` as good measure. Since I want this to run entirely non-interactively, prompting the user doesn't work for me. But, I'm not totally sure my understand is correct here.

Thanks,
Jay

**Comment by InAnimaTe** [comment]
rTorrent is a bear. It really is. When it dies, it dies hard, with a vengeance. 

My thoughts are that the container should never stop if rtorrent dies. So moving toward a healthcheck model is probably smart. Even better is if the xmlrpc tools can just keep a connection open with rtorrent and if the connection dies, try once more, and if still down, fail, which then invokes a re-launch (first clearing lock files or zombie processes).

**Comment by jaysh** [comment]
Rightly said!

The issue with a persistent connection is the state of the socket doesn't hint to us that anything is wrong. It's only when you try to write data to it, you realise there's nobody on the other side responding. That's pretty much why there's a 10 second timeout on Nginx side, so that it closes the connection in reasonable time (the default is 60s). In my experience, the response will come back in <0.01s, if it's going to come back at all.

Given that, I think the current healthcheck solution is quite reliable. I've been running it for a few days and it's been rock solid for me.

FWIW, my fix for the restarting is this: https://github.com/jaysh/docktorrent/commit/3cf7650c6733873557b0634dfc2c40a7fd99915e

**Comment by kfei** [comment]
@jaysh ,
Thanks for coming again :) And yes you're totally correct, I should remove automatic restarting from the feature list right after I introduced the s6 process supervisor and its `finish` hook. Can we discuss your solution in more detail on its PR page #8? 

@InAnimaTe ,
Thank you. I think a healthcheck script to work around rTorrent's random unresponsive issue is required.

**Comment by kfei** [comment]
Closed by #8
